# Generated by Django 2.0.1 on 2018-01-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(default='kk', max_length=16)),
                ('sex', models.CharField(default='man', max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('introduce', models.TextField()),
                ('birth', models.DateField()),
            ],
        ),
    ]
