# Generated by Django 2.0.1 on 2018-02-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180112_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomments',
            options={'verbose_name': '课程评论', 'verbose_name_plural': '课程评论'},
        ),
        migrations.AlterModelOptions(
            name='userask',
            options={'verbose_name': '用户咨询', 'verbose_name_plural': '用户咨询'},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户课程', 'verbose_name_plural': '用户课程'},
        ),
        migrations.AlterModelOptions(
            name='userfavorite',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '消息', 'verbose_name_plural': '消息'},
        ),
    ]
